# Generated by Django 2.1.3 on 2018-12-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181225_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
